using System.Text;

namespace SkyrimFair.Generator;

/// <summary>
/// The generated list of every stall: number, trade (the name its keeper carries in game),
/// lane, position, shell and the goods its kit lays out, so a stall seen in game can be
/// found here and its props changed in fairWorld.market.stallKits.
/// </summary>
internal static class StallDirectory
{
    public static string Write(MarketResult market, FairWorldConfig world)
    {
        var names = world.Vendors.ThemeNames;
        var kits = world.Market.StallKits;
        var b = new StringBuilder();
        b.AppendLine("# Stall directory");
        b.AppendLine();
        b.AppendLine("Generated by the generator from `fair.config.json` on every build; do not edit by hand.");
        b.AppendLine("Each stall's keeper carries the stall's name in game. In the console, `player.moveto` a");
        b.AppendLine("stall's marker to go to it. Change a stall's goods in `fairWorld.market.stallKits`");
        b.AppendLine("(by theme) and `fairWorld.market.vignettes`. The numbers match the map in");
        b.AppendLine("`docs/images/stalls_map.png` (drawn from the plugin; redraw it after a layout change).");
        b.AppendLine();
        b.AppendLine("![Stall map](images/stalls_map.png)");
        b.AppendLine();
        b.AppendLine("| # | Stall | Theme | Lane | At (x, y) | Shell | Counter goods | Beside / behind | Sign |");
        b.AppendLine("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
        var i = 0;
        foreach (var s in market.Stalls.OrderBy(s => s.Lane, StringComparer.Ordinal).ThenBy(s => s.Y).ThenBy(s => s.X))
        {
            i++;
            var kit = kits.FirstOrDefault(k => k.Themes.Contains(s.Theme));
            var name = names.TryGetValue(s.Theme, out var n) ? n : s.Theme;
            b.AppendLine($"| {i} | {name} | `{s.Theme}` | {s.Lane} | {s.X:0}, {s.Y:0} | {s.Module} | " +
                $"{(kit is null ? "-" : string.Join(", ", kit.Counter.Distinct()))} | " +
                $"{(kit is null ? "-" : string.Join(", ", kit.Side.Concat(kit.Rear).Distinct()))} | " +
                $"{(kit is null || kit.Sign.Count == 0 ? "-" : string.Join(", ", kit.Sign))} | `{s.MarkerEditorId}` |".Replace(" | `" + s.MarkerEditorId + "` |", " |"));
        }

        var placed = market.Stalls.Select(s => s.Theme).ToHashSet();
        var spare = names.Where(kv => !placed.Contains(kv.Key)).Select(kv => $"{kv.Value} (`{kv.Key}`)").ToList();
        if (spare.Count > 0)
        {
            b.AppendLine();
            b.AppendLine("## Kits ready but not placed");
            b.AppendLine();
            b.AppendLine("These trades have kits and keeper names but no stall yet (the site fits " + market.Stalls.Count + "):");
            b.AppendLine();
            foreach (var x in spare) b.AppendLine($"- {x}");
        }

        b.AppendLine();
        b.AppendLine("## Markers");
        b.AppendLine();
        b.AppendLine("| # | Stall | Marker (`player.moveto`) |");
        b.AppendLine("| --- | --- | --- |");
        i = 0;
        foreach (var s in market.Stalls.OrderBy(s => s.Lane, StringComparer.Ordinal).ThenBy(s => s.Y).ThenBy(s => s.X))
        {
            i++;
            b.AppendLine($"| {i} | {(names.TryGetValue(s.Theme, out var n) ? n : s.Theme)} | `{s.MarkerEditorId}` |");
        }

        return b.ToString().Replace("\r\n", "\n");
    }
}
